#!/usr/bin/env bash
if curl https://www.google.com &> /dev/null ; then
	echo internet
else 
	echo no hay internet
fi	
#inline
#curl https://www.google.com &> /dev/null && echo internet||echo no hay intenet
